services:
  documentation:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    container_name: documentation
    network_mode: "host"
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ./:/workspace
      - ~/.ssh:/home/user/.ssh
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
