name: manual-package

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build static files
        run: make html

      - name: Add .nojekyll file
        run: touch build/html/.nojekyll

      - name: Compress build/html to build-html.zip
        run: |
          cd build
          zip -r ../build-html.zip html

      # 可选：上传 zip 文件为 workflow 的 Artifacts，方便在 GitHub Actions 界面下载
      - name: Upload build-html.zip as artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-html
          path: build-html.zip
