name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs every day at midnight german time
  schedule:
    - cron: '0 22 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Install
        run: pip install -r requirements.txt
      -
        name: Build
        run: make html
      -
        name: Nojekyll
        run: touch build/html/.nojekyll
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
