name: deploy

# 只保留手动触发
on:
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取代码（含子模块）
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # 2. 安装依赖
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 3. 构建 HTML
      - name: Build HTML
        run: make html

      # 4. 创建 .nojekyll（可选，保留原行为）
      - name: Add .nojekyll
        run: touch build/html/.nojekyll

      # 5. 打包为 zip
      - name: Package site
        run: |
          cd build/html
          zip -r ../site.zip .
          cd ../..
          echo "site.zip 已生成，大小：$(du -h site.zip | cut -f1)"

      # 6. 上传 Artifact（手动下载）
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-zip
          path: build/site.zip
          retention-days: 7   # 保存 7 天，可自行调整
